# Perfil PROD: Google Cloud Serverless Managed Services
google.cloud.project-id=${GCP_PROJECT_ID}
spring.cloud.gcp.secretmanager.enabled=true

# BigQuery Particionado Obligatorio & FinOps
bigquery.dataset=proyectoemergencygeogridcrisis_analytics
logging.level.com.corp=INFO
