steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoFleetColdChain'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-fleet-cold-chain:latest', 'apps/ProyectoFleetColdChain']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-fleet-cold-chain:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-fleet-cold-chain:latest'
