steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoSubSurfaceGeoTwin'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-sub-surface-geo-twin:latest', 'apps/ProyectoSubSurfaceGeoTwin']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-sub-surface-geo-twin:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-sub-surface-geo-twin:latest'
