steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoSubSurfaceGeoTwin'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-sub-surface-geo-twin:beta', 'apps/ProyectoSubSurfaceGeoTwin']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-sub-surface-geo-twin:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-sub-surface-geo-twin:beta'
