steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoRutasSenderismoGR'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-rutas-senderismo-gr:latest', 'apps/ProyectoRutasSenderismoGR']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-rutas-senderismo-gr:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-rutas-senderismo-gr:latest'
