steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoEnoturismoRutasVino'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-enoturismo-rutas-vino:beta', 'apps/ProyectoEnoturismoRutasVino']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-enoturismo-rutas-vino:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-enoturismo-rutas-vino:beta'
