steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoHeritageDigitalTwin3D'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-heritage-digital-twin-3d:latest', 'apps/ProyectoHeritageDigitalTwin3D']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-heritage-digital-twin-3d:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-heritage-digital-twin-3d:latest'
