steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoZeroTrustOTMesh'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-zero-trust-ot-mesh:latest', 'apps/ProyectoZeroTrustOTMesh']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-zero-trust-ot-mesh:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-zero-trust-ot-mesh:latest'
