steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoGlobalCruiseMRV'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-global-cruise-mrv:latest', 'apps/ProyectoGlobalCruiseMRV']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-global-cruise-mrv:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-global-cruise-mrv:latest'
