steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoPresaTwinSCADA'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-presa-twin-scada:beta', 'apps/ProyectoPresaTwinSCADA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-presa-twin-scada:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-presa-twin-scada:beta'
