steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoIndustrialMicrogridMPC'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-industrial-microgrid-mpc:beta', 'apps/ProyectoIndustrialMicrogridMPC']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-industrial-microgrid-mpc:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-industrial-microgrid-mpc:beta'
