steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoIndustrialMicrogridMPC'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-industrial-microgrid-mpc:latest', 'apps/ProyectoIndustrialMicrogridMPC']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-industrial-microgrid-mpc:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-industrial-microgrid-mpc:latest'
