steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoFiestasInteresTuristico'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-fiestas-interes-turistico:latest', 'apps/ProyectoFiestasInteresTuristico']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-fiestas-interes-turistico:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-fiestas-interes-turistico:latest'
