# Perfil LOCAL: Emuladores y Mocks en Memoria
google.cloud.project-id=itinera-local
firestore.emulator.host=localhost:8089
bigquery.emulator.host=http://localhost:8086

# Telemetría e Ingesta Local
pct.telemetry.in-memory=true
logging.level.com.corp=DEBUG
