steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoCircularTextileDPP'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-circular-textile-dpp:beta', 'apps/ProyectoCircularTextileDPP']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-circular-textile-dpp:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-circular-textile-dpp:beta'
