steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoCircularTextileDPP'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-circular-textile-dpp:latest', 'apps/ProyectoCircularTextileDPP']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-circular-textile-dpp:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-circular-textile-dpp:latest'
