steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoSmartStreetLightingV2G'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-smart-street-lighting-v2g:beta', 'apps/ProyectoSmartStreetLightingV2G']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-smart-street-lighting-v2g:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-smart-street-lighting-v2g:beta'
