steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoDroneAirspaceUSpace'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-drone-airspace-uspace:beta', 'apps/ProyectoDroneAirspaceUSpace']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-drone-airspace-uspace:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-drone-airspace-uspace:beta'
