steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoGovProcureMatch'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-gov-procure-match:beta', 'apps/ProyectoGovProcureMatch']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-gov-procure-match:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-gov-procure-match:beta'
