steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoGovProcureMatch'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-gov-procure-match:latest', 'apps/ProyectoGovProcureMatch']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-gov-procure-match:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-gov-procure-match:latest'
