steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoPlayasInteligentesCostas'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-playas-inteligentes-costas:latest', 'apps/ProyectoPlayasInteligentesCostas']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-playas-inteligentes-costas:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-playas-inteligentes-costas:latest'
