steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoPlayasInteligentesCostas'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-playas-inteligentes-costas:beta', 'apps/ProyectoPlayasInteligentesCostas']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-playas-inteligentes-costas:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-playas-inteligentes-costas:beta'
