steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoMiceConferenceTwin'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-mice-conference-twin:beta', 'apps/ProyectoMiceConferenceTwin']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-mice-conference-twin:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-mice-conference-twin:beta'
