steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoMiceConferenceTwin'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-mice-conference-twin:latest', 'apps/ProyectoMiceConferenceTwin']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-mice-conference-twin:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-mice-conference-twin:latest'
