steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoCriticalMineralsMRV'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-critical-minerals-mrv:latest', 'apps/ProyectoCriticalMineralsMRV']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-critical-minerals-mrv:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-critical-minerals-mrv:latest'
