steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoQuantumResistantRWA'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-quantum-resistant-rwa:latest', 'apps/ProyectoQuantumResistantRWA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-quantum-resistant-rwa:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-quantum-resistant-rwa:latest'
