steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoHotelTwinRevPAR'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-hotel-twin-revpar:latest', 'apps/ProyectoHotelTwinRevPAR']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-hotel-twin-revpar:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-hotel-twin-revpar:latest'
