steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoHotelTwinRevPAR'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-hotel-twin-revpar:beta', 'apps/ProyectoHotelTwinRevPAR']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-hotel-twin-revpar:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-hotel-twin-revpar:beta'
