steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoPortTwinAutonomous'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-port-twin-autonomous:beta', 'apps/ProyectoPortTwinAutonomous']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-port-twin-autonomous:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-port-twin-autonomous:beta'
