steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoCaminoSantiagoXacobeo'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-camino-santiago-xacobeo:beta', 'apps/ProyectoCaminoSantiagoXacobeo']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-camino-santiago-xacobeo:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-camino-santiago-xacobeo:beta'
