steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoAirlineInterlineBaggage'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-airline-interline-baggage:latest', 'apps/ProyectoAirlineInterlineBaggage']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-airline-interline-baggage:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-airline-interline-baggage:latest'
