steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoAirlineInterlineBaggage'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-airline-interline-baggage:beta', 'apps/ProyectoAirlineInterlineBaggage']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-airline-interline-baggage:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-airline-interline-baggage:beta'
