<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.corp.tenant</groupId>
        <artifactId>corp-spring-boot-starter-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../../corp-spring-boot-starter/pom.xml</relativePath>
    </parent>
    <groupId>com.pct.ecosystem</groupId>
    <artifactId>core-sync-mesh</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>core-sync-mesh</name>
    <description>Motor de sincronización offline bidireccional basado en CRDTs deterministas para Java 25</description>

    <dependencies>
        <dependency>
            <groupId>com.corp.tenant</groupId>
            <artifactId>corp-contracts-starter</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>