steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoSeamlessIntermodalHub'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-seamless-intermodal-hub:beta', 'apps/ProyectoSeamlessIntermodalHub']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-seamless-intermodal-hub:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-seamless-intermodal-hub:beta'
