steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoAstroturismoStarlight'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-astroturismo-starlight:latest', 'apps/ProyectoAstroturismoStarlight']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-astroturismo-starlight:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-astroturismo-starlight:latest'
