steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoPharmaColdChain'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-pharma-cold-chain:beta', 'apps/ProyectoPharmaColdChain']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-pharma-cold-chain:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-pharma-cold-chain:beta'
