steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoSoilBioCarbonTwin'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-soil-bio-carbon-twin:beta', 'apps/ProyectoSoilBioCarbonTwin']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-soil-bio-carbon-twin:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-soil-bio-carbon-twin:beta'
