apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: proyecto-quantum-resistant-r-w-a
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/execution-environment: "gen2"
    spec:
      containerConcurrency: 250
      containers:
        - image: europe-west1-docker.pkg.dev/corp-ecosystem/proyecto-quantum-resistant-r-w-a:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
