steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "echo 'Iniciando despliegue PRO de servicio ${_SERVICE_NAME}'"]
    id: "Log Service Info"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest",
        ".",
      ]
    id: "Build JVM Image"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest",
      ]
    id: "Push Image"
    waitFor: ["Build JVM Image"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--cpu",
        "2.0",
        "--memory",
        "2Gi",
        "--concurrency",
        "300",
        "--cpu-boost",
        "--cpu-throttling",
        "--timeout",
        "600",
        "--no-allow-unauthenticated",
        "--min-instances",
        "0",
        "--max-instances",
        "10",
        "--service-account",
        "${_SA_EMAIL}",
        "--update-env-vars=SPRING_PROFILES_ACTIVE=prod,GCP_PROJECT_ID=${_PROJECT_ID},JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCompactObjectHeaders -XX:+UseZGC -XX:+ZGenerational -XX:+ExitOnOutOfMemoryError -Xms512m -Xmx1536m",
      ]
    id: "Deploy Service"
    waitFor: ["Push Image"]

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest"

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: "tokenrwa-backend-prod"
  _IMAGE_NAME: "tokenrwa-backend"
  _PROJECT_ID: "ecosistema-prod"
  _REPO_NAME: "ecosystem-repo-prod"
  _SA_EMAIL: "tokenrwa-backend-prod-sa@ecosistema-prod.iam.gserviceaccount.com"
  _REGION: "europe-west1"
