apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: proyecto-b2g
spec:
  template:
    spec:
      containers:
        - image: gcr.io/proyecto/b2g:latest
          resources:
            limits:
              memory: 512Mi
