steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "echo 'Iniciando despliegue BETA de servicio ${_SERVICE_NAME}'"]
    id: "Log Service Info"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ecosystem-repo/${_IMAGE_NAME}:beta",
        ".",
      ]
    id: "Build JVM Image"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ecosystem-repo/${_IMAGE_NAME}:beta",
      ]
    id: "Push Image"
    waitFor: ["Build JVM Image"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ecosystem-repo/${_IMAGE_NAME}:beta",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--cpu",
        "1.0",
        "--memory",
        "512Mi",
        "--concurrency",
        "100",
        "--cpu-boost",
        "--cpu-throttling",
        "--timeout",
        "600",
        "--no-allow-unauthenticated",
        "--min-instances",
        "0",
        "--max-instances",
        "2",
        "--service-account",
        "${_SA_EMAIL}",
        "--update-env-vars=SPRING_PROFILES_ACTIVE=beta,GCP_PROJECT_ID=${_PROJECT_ID},JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -XX:TieredStopAtLevel=1 -XX:+ExitOnOutOfMemoryError -Xms256m -Xmx512m",
      ]
    id: "Deploy Service"
    waitFor: ["Push Image"]

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ecosystem-repo/${_IMAGE_NAME}:beta"

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: "vpp-backend-beta"
  _IMAGE_NAME: "vpp-backend"
  _PROJECT_ID: "ecosistema-beta"
  _SA_EMAIL: "vpp-backend-beta-sa@ecosistema-beta.iam.gserviceaccount.com"
  _REGION: "europe-west1"
