steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoAirportTouristIntermodal'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-airport-tourist-intermodal:latest', 'apps/ProyectoAirportTouristIntermodal']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-airport-tourist-intermodal:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-airport-tourist-intermodal:latest'
