steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoSmartDestinationDTI'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-smart-destination-dti:latest', 'apps/ProyectoSmartDestinationDTI']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-smart-destination-dti:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-smart-destination-dti:latest'
