# cloudbuild.yaml - Pipeline SLSA L3 & Cosign para ProyectoCyanobacteriaBioNitrogenFertilizer
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=europe-west1-docker.pkg.dev/$PROJECT_ID/ecosystem-repo/proyectocyanobacteriabionitrogenfertilizer:$SHORT_SHA'
      - '--cache=true'
      - '--dockerfile=Dockerfile'

  - name: 'anchore/syft:latest'
    args:
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ecosystem-repo/proyectocyanobacteriabionitrogenfertilizer:$SHORT_SHA'
      - '-o'
      - 'cyclonedx-json'
      - '--file'
      - 'sbom.json'

  - name: 'gcr.io/projectsigstore/cosign:latest'
    env:
      - 'COSIGN_EXPERIMENTAL=1'
    args:
      - 'sign'
      - '--yes'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ecosystem-repo/proyectocyanobacteriabionitrogenfertilizer:$SHORT_SHA'
