steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoEmergencyGeoGrid'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-emergency-geogrid:latest', 'apps/ProyectoEmergencyGeoGrid']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-emergency-geogrid:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-emergency-geogrid:latest'
