steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoParquesNacionalesNatura2000'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-parques-nacionales-natura2000:beta', 'apps/ProyectoParquesNacionalesNatura2000']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-parques-nacionales-natura2000:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-parques-nacionales-natura2000:beta'
