steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoEcoTourismPassport'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-eco-tourism-passport:beta', 'apps/ProyectoEcoTourismPassport']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-eco-tourism-passport:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-eco-tourism-passport:beta'
