steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoCascoHistoricoCrowd'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-casco-historico-crowd:latest', 'apps/ProyectoCascoHistoricoCrowd']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-casco-historico-crowd:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-casco-historico-crowd:latest'
