steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoTurismoTermalBalnearios'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-turismo-termal-balnearios:latest', 'apps/ProyectoTurismoTermalBalnearios']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-turismo-termal-balnearios:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-turismo-termal-balnearios:latest'
