steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'apps/ProyectoAgroEnergyVPP'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-agro-energy-vpp:latest', 'apps/ProyectoAgroEnergyVPP']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-agro-energy-vpp:latest']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-agro-energy-vpp:latest'
