steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    dir: 'apps/ProyectoClinicalTrialsZK'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-clinical-trials-zk:beta', 'apps/ProyectoClinicalTrialsZK']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-clinical-trials-zk:beta']
images:
  - 'gcr.io/$PROJECT_ID/proyecto-clinical-trials-zk:beta'
